spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:loansdb
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9005
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
info:
  app:
    name: loans
    description: Newton Apple Loans MS
  version: 1.0.0
  location: Hyderabad
